evervault/enclaves

control-plane/src/egressproxy.rs

IP checks for egress should be more restrictive
- Use built in `std::net` ip checks where possible
- Validate octets according to IANA docs otherwise
- Add tests

Tighten restrictions on egress IPs

---

data-plane/src/dns/enclavedns.rs
data-plane/src/dns/error.rs

The dns proxy is shutting down on error
On error, log issue and continue

Fix enclave dns error handling

---

control-plane/src/health.rs

Deep healthchecks are default on, and were previously configurable. Removing the config is an unnecessary breaking change.
Add support for `DISABLE_DEEP_HEALTHCHECKS` which lets us turn off requests into the enclave during host healthchecks.

Add support for turning off deep healthchecks

---

README.md

sometimes vscode error checking stops working
Add a note to relevant setting in readme
took me longer than I would've have liked 😅

add check target note to readme

---

Cargo.lock
data-plane/Cargo.toml
data-plane/src/acme/mod.rs
data-plane/src/server/data_plane_server.rs
data-plane/src/server/tls/tls_server.rs

Add the tls public key to the attestation docs
Add the pub key bytes

Add public key to attestation doc

---

data-plane/src/utils/trx_handler.rs

Cage trx logging is another source of resource contention for our vsock channel. Producing Trx logs less frequently will reduce the amount of congestion at the expense of storing more logs in memory (for a maximum of 30s).
- Expand buffer capacity from 10 logs to 20
- Update logger interval to 30 seconds

Reduce frequency of Cage trx logging

---

data-plane/src/main.rs
data-plane/src/server/data_plane_server.rs
e2e-tests/package-lock.json
e2e-tests/package.json

Resolve dependabot alerts
Bump chai deps

chore: bump e2e tests dependency for get-func-name

---

Cargo.lock

Pull in patch for https://cwe.mitre.org/data/definitions/476.html
run cargo update

Cargo update to pull in security patches

---

.github/workflows/deploy-data-plane-binary-staging.yml

Theres no semver in staging so publishing doesn't make sense
Remove step

Dont push runtime version in staging

---

.github/workflows/deploy-data-plane-binary-production.yml
.github/workflows/deploy-runtime-installer.yml

Version tagging steps need checkout action to pull scripts
Add actions/checkout@v2 to steps

Add checkout to action

---

.github/workflows/deploy-runtime-installer.yml

The version wasn't being resolved
Add dependency to version job

Add version dependency to installer action

---

Cargo.lock
control-plane/Cargo.toml
data-plane/Cargo.toml

The package version is out of sync with the latest release
Update on V0 branch

Fix Cargo package version

---

data-plane/src/acme/directory.rs

Add a short description about this PR.
Add links to issues, tech plans etc.
Describe how you've approached the problem

Add logs for if acme request fails

---

data-plane/src/acme/directory.rs

Need logs in acme calls to figure out why it's failing
add logs

Merge updated logging to v0 branch

---

control-plane/src/config_server.rs
control-plane/src/configuration.rs
data-plane/src/acme/cert.rs
data-plane/src/config_client.rs
data-plane/src/error.rs
data-plane/src/lib.rs

Expand trusted cert hostnames to order for the new enclave domain.
Cherry pick #160

[SPE-986] Release provisioning of trusted cert for enclave to staging

---

data-plane/src/server/tls/cert_resolver.rs

Need to server the correct cert for enclave.com|dev
Cherry pick #163

Release handling enclave.evervault.com in cert SNI resolver to staging

---

control-plane/src/health.rs

As the is_draining flag was global it made the tests indeterministic depending when the test that set the onceLock was called.
Move accessing the OnceLock out of the run_ecs_health_check_service function and pass the flag as a param. Allows us to test the logic without having to set the OnceLock.

Fix flaky OnceLock test

---

data-plane/src/server/layers/auth.rs

Deprecating global keys for v1
- Remove fallback logic in authentication layer
- Update tests to assert that 401 is returned to the user

Update auth layer to remove the global api key fallback

---

control-plane/src/config_server.rs

Log when there's an error getting token
Log

Log error on token get failure

---

control-plane/src/configuration.rs

Revert provisioner hostname
Revert

Revert cert provisioner name change

---

.github/workflows/deploy-runtime-installer-production.yml
.github/workflows/deploy-runtime-installer-staging.yml
.github/workflows/deploy-runtime-installer.yml
control-plane/src/clients/mtls_config.rs

Deploy installer to staging on push to main
Separate staging and production publishing

Separate installer deployment

---

.github/workflows/deploy-runtime-installer.yml
scripts/update-installer-version.sh

It was pulling the version json from production
Pull from .io in staging

Fix staging installer publish

---

control-plane/src/dnsproxy.rs

Most clients will attempt retries on DNS timeout, which renders the control plane retries ineffective.
Shuffle the DNS providers in the control plane per connection to make client retries more effective.

Shuffle dns providers to handle client side retries more effectively

---

.github/workflows/lint.yml
Cargo.lock
data-plane/Cargo.toml
data-plane/src/dns/enclavedns.rs
data-plane/src/dns/error.rs
shared/Cargo.toml
shared/src/server/egress.rs

Reverts evervault/enclaves#226
Needs more thorough testing

Revert "Use cached dns results in data plane"

---

data-plane/src/server/layers/decrypt.rs

The og encrypted strings weren't being picked up by the regex
update regex and add test

update regex for ev encrypted strings

---

.github/workflows/deploy-control-plane-image-production.yml
.github/workflows/deploy-control-plane-image-staging.yml
.github/workflows/lint.yml
shared/src/server/health.rs

Syntax error in workflow file and failed test that didn't run until merge
fix

Fix failing merge workflows

---

data-plane/src/dns/egressproxy.rs

This log is pointless and is noisy
Remove

Remove log

---

.github/workflows/deploy-control-plane-image-production.yml
.github/workflows/deploy-data-plane-binary-production.yml

Missed some credentials further down in the workflow
Update them as well

Fix aws credentials again

---

Cargo.lock
e2e-tests/mock-crypto/Cargo.toml

Bumping Ring to remove vulnerability

Patching ring
