.gitignore, e2e-tests/mock-crypto/Cargo.toml
Prevent tracking of cargo lock and allow internal crypto lib to pull newer versions
Unpin crypto lib, add cargo lock to gitignore
=> Unpin internal crypto lib, add cargo lock to gitignore

data-plane/src/server/data_plane_server.rs
Trx logs shouldn't be logged when trx_logging is disabled but debug mode is on.
Stop logging trx_logs in the enclave when trx_logging turned off. This also means the control plane can validate trx logs before been shipped to ES.
=> [SPE-542] Don't send trx logs when in debug mode and trx_logging is switched off

control-plane/src/config_server.rs, control-plane/src/configuration.rs, shared/src/logging.rs
A cage could override the trx context ev tenant details. We need to validate them in the control plane.
Introduce a cage_context to the control plane instead of pulling env vars on every read. 
Use this cage context to check app, team, cage uuid and name when loggin trx context.
=> [SPE-541] Validate cage and ev tenant details before logging a trx context

Dockerfile, data-plane/src/configuration.rs, data-plane/src/dns/egressproxy.rs, data-plane/src/dns/error.rs, data-plane/src/env/mod.rs, data-plane/src/main.rs, e2e-tests/customerProcess.js, e2e-tests/e2e.js
Add egress allowlist to the data plane so that attempts through the egress proxy fail if they are not allowlisted.
Enforcing it in the data plane first so it will be included in attestation. Later on it will be in the control plane too.
- Default behaviour to allow all egress if no settings present to allow backwards compatibility for the moment (*)
- Allow exact domain matching or wildcard eg. app.evervault.com or *.evervault.com
=> Enforce allowlist in data plane

Cargo.lock, data-plane/Cargo.toml
Vulns flagged in Openssl dependency 
Bump openssl dependency (no updates in changelog will impact cages)
=> Bump openssl dependency

data-plane/src/crypto/api.rs, data-plane/src/e3client/mod.rs, data-plane/src/env/mod.rs, data-plane/src/server/data_plane_server.rs, e2e-tests/mock-crypto/src/main.rs, e2e-tests/run-all-feature-tests.sh
We use the uuids provided in the token for authentication and the uuids aren't needed in E3
Remove
=> Remove uuids from crypto calls

data-plane/Cargo.toml, data-plane/src/crypto/attest.rs, data-plane/src/crypto/rand.rs, data-plane/src/dns/egressproxy.rs, data-plane/src/error.rs, data-plane/src/utils/mod.rs, data-plane/src/utils/nsm.rs
The nitro security module exposes raw file descriptors via its driver api. The RawFD is not tidied up currently (using the nsm_exit function).
This PR adds an NsmConnection type which handles the creation of a connection to the NSM device, and has a custom drop implementation to tidy up. It is effectively acting as a small `OwnedFd` impl for NSM.
=> Improve API within Cages for the Nitro Security Module

data-plane/src/configuration.rs, data-plane/src/main.rs
Need to conditionally support proxy protocol passthrough when TLS Termination is disabled
Check if `FORWARD_PROXY_PROTOCOL` is set, and if it is forward the header on the connection
=> Support proxy protocol when TLS termination is disabled

scripts/start-cage.sh
First part of improvement to deployment. Should only try to kill the existing enclave if it's running. Another PR will start killing the enclave when a sigterm is retrieved. This will speed up the time it takes a cage to start.
Use the nitro-cli to describe-enclaves and check if there's an enclave running. If there is, kill it and sleep. If not continue.
=> [SPE-616] Check if enclave is running before attempting to kill it

control-plane/src/main.rs
We should kill the enclave when we're terminating the task rather than when the new task starts up.
When sigterm received, wait 55 seconds then kill enclave. It's 55 seconds as ECS kills the container after 60s after receiving the sigterm.
=> [SPE-617] Kill enclave when sigterm retrieved

data-plane/src/server/data_plane_server.rs
Return ClientError to client when decryption request to E3 fails. It will reveal if the issue was with deserialisation/network/bad request when two enclaves are talking to each other and otherwise have no logging
Return the error in the response
=> Return decryption failure error to client

Dockerfile, control-plane/src/egressproxy.rs, data-plane/src/configuration.rs, data-plane/src/dns/egressproxy.rs, data-plane/src/env/mod.rs, data-plane/src/lib.rs, data-plane/src/main.rs, data-plane/src/server/data_plane_server.rs, data-plane/src/server/tls/cert_resolver.rs, docker-compose.yml, e2e-tests/run-all-feature-tests.sh, e2e-tests/scripts/start-data-plane.sh, shared/src/server/egress.rs
Squashing the docker layers for repro builds causes ENV directives to be lost
- Read config from file instead
- For backwards compatibility with the CLI revert to checking env if file is not present
=> Read dataplane config from file

data-plane/src/e3client/mod.rs
Add logging to surface retry failure in debug mode cages
Print error on retry
=> Add logging on decryption failure

Cargo.lock, control-plane/Cargo.toml, control-plane/src/configuration.rs, control-plane/src/main.rs, shared/src/server/proxy_protocol.rs
Data planes without the ability to parse proxy protocol will fail to terminate TLS if it its present
- Add a check for an optional env var of the data plane semantic version
- If the version predates proxy protocol support, strip the header from the socket before forwarding
=> Add backwards compat for proxy protocol

data-plane/src/dns/enclavedns.rs, data-plane/src/dns/error.rs, data-plane/src/main.rs, shared/src/server/egress.rs
DNS Proxy in the data plane was handling lookups sequentially so was able to be choked by a failed lookup.
- Update Data plane's DNS Proxy to have better concurrency support (up to 250 lookups at a time)
- Add timeouts for all networking and sync channels within the DNS Proxy
- Add logs for observability into the DNS Proxy
There is a concurrency control applied using a semaphore (to prevent FD exhaustion) and an upper bound on the buffer of the DNS proxy's internal sync channel (to prevent an unbounded message buffer).
=> Improve in enclave dns proxy to prevent EAI again errors

scripts/start-cage.sh
Cage startup script calls the EC2 metadata API to get the current instance ID, but this call is failing due to a missing auth token
Add call to get short lived metadata token before calling for instance ID
=> Add call to get metadata token before calling for instance id

data-plane/src/config_client.rs
Need the methods in the config client in the data plane to send requests through the control plane under to S3.
Added the methods which need to be used to persist acme materials:
- get_object
- put_object 
- delete_object
=> [SPE-780] Add config client methods for storage

data-plane/src/lib.rs, data-plane/src/server/data_plane_server.rs, shared/src/logging.rs
Add support in the data plane for custom trusted headers
- Add trusted headers to the Feature Context type
- Let the logging logic retain the header values for the customer defined `trusted_headers`. A header will be considered trusted if its: 
- in the list of known headers
- has an absolute match in the list of trusted headers
- matches a wildcard in the trusted headers (wildcards allow for suffix matching only).
=> Update the data plane to pull the trusted headers from env

data-plane/src/lib.rs, shared/src/logging.rs
Trusted headers is to be used for observability, and should not be used to record credentials sent in Cage requests. The initial implementation allowed an arbitrary list of headers to be used without any additional checks.
- Add a set of known sensitive headers which should not be recorded. Obfuscate any header which matches them.
- Map all trusted headers to lowercase to avoid case mismatch
=> Update trusted headers to prevent credentials being recorded

.github/workflows/lint.yml, .github/workflows/test-control-plane.yml, .github/workflows/test-data-plane.yml, .github/workflows/test-shared-lib.yml
Cages CI had a lot of repetition:
- We had a common lint workflow, but each package also ran its own linter
- The shared library never triggered a test/compile on the control-plane/data-plane
- The shared library wasn't tested
- Remove lint step from individual packages
- Add trigger for control plane and data plane CI for changes to shared lib
- Add shared lib CI
=> Restructure Cages CI

shared/src/logging.rs
Migration from hyper request type to the http crate's request type changed the value being recorded in Cage logs
- Update uri value set in Trx logs to only contain the path and query param
- Add tests to uri formatting
=> Correct uri recorded in cage logs

control-plane/src/e3proxy.rs, data-plane/src/server/data_plane_server.rs, e2e-tests/websocketTests.js
Return 401 for unauthed websocket requests
Return 401 response
=> Return 401 for websockets

Cargo.lock, data-plane/src/error.rs, data-plane/src/server/data_plane_server.rs, data-plane/src/utils/trx_handler.rs, shared/Cargo.toml, shared/src/logging.rs
Add logs for non HTTP requests
- For WS request, add all HTTP info that comes in upgrade request
- Log only if log creation/send fails, dont affect request
- Any other request will be classified as TCP as catchall
- No response info or request times because we blind pipe non http requests 
- Added 401 status code for non HTTP requests when auth fails - kind of weird for TCP case, can change if people feel strongly about it but can format this differently in the UI because the enum will specify the request type
=> Non http trx logs

data-plane/src/error.rs, data-plane/src/server/data_plane_server.rs
Data plane request parsing wasn't accounting for content length, resulting intermittent incomplete bodies being forwarded to wrapped services.
Update `build_http_request` to take in the incoming stream, evaluate the content length, and read until the full payload is in memory before forwarding
=> Update data plane request parsing

data-plane/src/error.rs, data-plane/src/server/data_plane_server.rs
In the new attestation flow we want the attestation document available to clients at <cage-url>/.well-known/attestation.
The AD will now contain the cage's cert and an expiry time
Break out of normal request handling flow on requests to .well-known and handle seperately
=> markd/handle requests to .well-known/attestation

Cargo.lock, control-plane/Cargo.toml, control-plane/src/clients/cert_provisioner.rs
Webpki has a known vulnerability reported in [webpki#69](https://github.com/briansmith/webpki/issues/69). The rustls team have forked webpki for their own create, which is used from rustls 0.24.0 onwards.
Updating rustls dependency to remove dep on vulnerable webpki crate
=> chore: move to rustls maintained webpki crate

acme-server/Dockerfile, acme-server/src/server.rs, task-definitions/acme-server/staging.json
Need root to run on 80 in the container so changing port to 8080 so that only the frontend router listens on port 80.
Update docker file to expose 8080 and update axum to listen on 8080
=> Change port in acme server

control-plane/Cargo.toml
S3 calls failing with no error message
Bump to version which logs
=> Bump storage-client-interface which has logs

data-plane/src/acme/cert.rs
Certificates are being provisioned and stored in the cage but the encoding is wrong and the TLS handshake fails. The cert returned from E3 decrypted isn't matching the cert pulled directly from zerossl 
```bash
curl https://trustable-cage.app-511b16ff81fa.cage.evervault.dev/decrypt -H "Content-Type: application/json"                                                                                             
curl: (35) LibreSSL/3.3.6: error:0DFFF0A8:asn1 encoding routines:CRYPTO_internal:wrong tag
```
Print certs as they're received from zerossl to debug
=> Add debug log to see certificate before parsed and encrypted

data-plane/src/env/mod.rs, data-plane/src/server/error.rs, data-plane/src/server/tls/tls_server.rs
If ordering a trusted cert fails, the ecs health check still reports as healthy as the EV_CAGE_INITIALIZED var has been written which makes the cage pass health checks.
Move writing the `EV_CAGE_INITIALIZED` to after trusted cert is ordered.
=> Move writing init complete vars to after trusted cert

data-plane/src/env/mod.rs
The provisioner returns the `EV_CAGE_INITIALIZED` env var. We now need to delay that been written until the trusted cert has also being provisioned/returned. 
Filter it out of secrets returned from provisioner. Ideally we could've removed it from the provisioner but older runtimes depend upon it being there
=> [SPE-846] Don't write env init var returned from provisioner

data-plane/src/acme/cert.rs
We need to renew trusted certs frequently as they are only valid for 90 days.
When pulling in the cert on startup, check if a renewal is needed and if so continue with the order process as if the cert didn't exist.
Broke out the conversion to x509s into it's own function to pass into each of the required functions:
* cert_renewal_needed
* to_certified_key
=> Check cert expiry after pulling cert and renew if expires in the next 30 days

data-plane/src/server/data_plane_server.rs, e2e-tests/e2e.js, e2e-tests/httpCustomerProcess.js
Data plane is using a hyper client to forward requests into the user process. When the response is chunked, the hyper client is building the chunked response and returning it complete. The transfer encoding header is still being returned however which breaks when received by the client. 
Remove transfer-encoding header on response returned from user process. Short term fix, long term would be to support passing a chunked stream back to the end user.
=> [SPE-884] Strip transfer encoding header on response in data plane

.github/workflows/vsock-proxy.yml, Cargo.lock, Cargo.toml, crates/vsock-proxy/Cargo.toml, crates/vsock-proxy/README.md, crates/vsock-proxy/src/main.rs, crates/vsock-proxy/src/net.rs
When testing Cages, it's useful to be able to spin up a simple proxy on the host EC2 instance. The brave nitro-shim of [gvproxy](https://github.com/brave-intl/bat-go/tree/master/nitro-shim/tools/gvproxy) and aws [vsock-proxy](https://github.com/aws/aws-nitro-enclaves-cli/blob/main/vsock_proxy/README.md) address this issue but are only concerned with tunnelling traffic out of the enclave.
The `vsock-proxy` crate makes no assumptions about whether TCP or Vsock should be treated as the server vs client. A proxy can be run to tunnel traffic from the host into the enclave using:
```sh
vsock-proxy --tcp-source 127.0.0.1:8008 --vsock-dest 1234:5678
```
Similarly a client can be run from the enclave to the host using:
```sh
vsock-proxy --vsock-source 3:6789 --tcp-dest 127.0.0.1:5000
```
- Add a …
=> Add vsock proxy crate

.github/workflows/deploy-control-plane-image-production.yml, .github/workflows/deploy-data-plane-binary-production.yml
Cages release workflows were triggered by tags pushed that matched `v*`. As a result, the new vsock-proxy crate's release flow will incorrectly trigger the Cage's release.
Update the tag pattern to assert that it is a semver-like string prefixed by `v`
=> Chore: Update cages release trigger to avoid conflict from vsock-proxy releases

.github/workflows/vsock-proxy.yml
Startswith wouldn't match for vsock-proxy releases
Use contains in place of startswith
=> Correct vsock-proxy release workflow

.github/workflows/vsock-proxy.yml, Cargo.lock, crates/vsock-proxy/Cargo.toml, crates/vsock-proxy/src/main.rs, crates/vsock-proxy/src/net.rs
vsock-proxy's dependency on a local, unpublished lib blocks the publish step
- Remove dependency on local shared lib
- Patch vsock-proxy workflow
=> vsock-proxy: Remove dependency on local shared lib

crates/vsock-proxy/Cargo.toml
Required fields before publishing
Add missing fields - license, description, authors, readme.
=> vsock-proxy: add missing metadata fields to cargo.toml

Cargo.lock, crates/vsock-proxy/Cargo.toml, crates/vsock-proxy/src/main.rs
A typo in the destination parsing caused a panic when proxying to a vsock destination
Correct destination parsing to handle vsock correctly
=> Fix destination parsing

Cargo.lock, crates/vsock-proxy/Cargo.toml, crates/vsock-proxy/src/main.rs
Runtime panics on start as it requires IO
Add IO to tokio runtime
=> vsock-proxy: fix runtime config

.github/workflows/test-e2e.yml, .github/workflows/vsock-proxy.yml, data-plane/src/main.rs
TCP Forwarding server within the data plane was not spawning child tasks for incoming connections which significantly reduced throughput.
Correct server by spawning new tokio tasks per connection
=> fix: update tcp forwarding server in data plane to spawn child tasks for incoming connections

Cargo.lock, data-plane/Cargo.toml, data-plane/src/acme/client.rs, data-plane/src/base_tls_client/tls_client_config.rs, shared/Cargo.toml
webpki-roots has been migrated away from a dependency on webpki (and in turn ring + untrusted). 
- Update webpki-roots to latest to remove unneeded deps
- Update shared lib's tokio-rustls dependency to latest
=> chore: bump remaining instances of tokio-rustls, use 0 dep version of webpki-roots

.github/workflows/test-control-plane.yml, .github/workflows/test-data-plane.yml, .github/workflows/test-e2e.yml, .github/workflows/test-runtime-builder.yml, .github/workflows/test-shared-lib.yml, .github/workflows/vsock-proxy.yml
Builds weren't being triggered in CI by changes in dependencies at the top level
Add Cargo.lock to the paths lists.
=> chore(ci): update trigger for workflows to account for lockfile

Cargo.lock, data-plane/Cargo.toml, data-plane/src/crypto/attest.rs
Updating chrono to the latest version led to certificate not_after values failing to parse on startup. 
- Update parsing to use both chrono and chrono_tz - chrono parses the time, and the timezone label is parsed by chrono_tz
- Add test for cert parsing
=> Fix: Cert "not_after" failing to parse

data-plane/src/health/agent.rs
Changes to healthcheck agent were merged too early, and their formatting was incorrect.
Format project
=> Chore: format healthcheck agent

.github/workflows/deploy-control-plane-image-staging.yml
Tag being pushed was using the semver variable as a suffix but the variable wasn't declared for the final step resulting in an incorrect tag.
Add semver variable to the final push step for the control plane.
=> fix: add missing semver variable to push step

.github/workflows/deploy-data-plane-binary-staging.yml, .github/workflows/scripts/update-runtime-version.sh
We are publishing a all latest versions for each major of the cage runtime, eventually this will also be used to mange deprecation
On release add the new version to the version json and publish to S3 where it will be served via cloudfront
Publish to runtime/versions
=> Publish to new version schema on deployment

data-plane/src/server/data_plane_server.rs
The Cage buffer wasn't being cleared correctly after handling a request.
Update check on bytes read from the socket to account for EOF, and clear the buffer on successful handling to reset the parse loop.
=> Clear buffer after handling request

.github/workflows/deploy-data-plane-binary-production.yml, .github/workflows/deploy-runtime-installer.yml
The CF cache isn't immediately invalidated on deployment
Add invalidation
=> Invalidate CF on production deployemt

data-plane/src/acme/cert.rs, data-plane/src/acme/key.rs, data-plane/src/base_tls_client/mod.rs, data-plane/src/cert_provisioner_client/mod.rs, data-plane/src/crypto/api.rs, data-plane/src/e3client/mod.rs
With the roll out of data policies, the crypto API in Cages needs to support the feature.
The Cage in enclave crypto API will forward an `x-evervault-data-role` header when set by the client
=> feat: forward x-evervault-data-role in calls to e3

data-plane/src/crypto/parser.rs
New ciphertext versions aren't parsed by the data plane stream parser
Add new ciphertext versions to stream parser
=> feat: add new ciphertext version to data plane parser

data-plane/src/env/mod.rs
Starting in v1, the cage's provisioner will only return the environment variables as configured for the cage and will not inject any vars to mark the cage as ready
Remove filters and old API Key env var
=> chore: remove bootstrap variable filters from data plane

.github/workflows/deploy-runtime-installer.yml
Runtime installer's checksum wasn't being pushed to staging, resulting in parse errors when trying to fetch latest
Update the installer's CI to push a checksum to staging
=> Add runtime checksum to version json object in staging

.github/workflows/deploy-runtime-installer.yml
Runtime installer release workflow didn't perform a git checkout before attempting to run the script
Add a checkout step
=> Add missing checkout step to runtime release workflow

.github/workflows/deploy-control-plane-image-staging.yml, .github/workflows/deploy-data-plane-binary-staging.yml, scripts/update-runtime-version.sh
Backporting changes to v0 release branch.
* update data plane staging release flow to be compatible with new semver flows
* chore: update staging release ci to use current semver suffixed with git sha
* chore: update runtime-version script to accept build assets hostname as an env var
=> Fix cages staging release workflow (#149)

.github/workflows/deploy-control-plane-image-production.yml, .github/workflows/deploy-control-plane-image-staging.yml, .github/workflows/deploy-data-plane-binary-production.yml, .github/workflows/deploy-data-plane-binary-staging.yml, .github/workflows/deploy-runtime-installer.yml, .github/workflows/test-runtime-builder.yml
CI on release/v0 branch wasn't firing for changes because branch triggers were wrong
- Update to trigger on push to release/v0
- Restrict release workflows to only accept tags with the frozen major version (0)
=> chore: update ci actions to trigger for changes to release/v* branch

Cargo.lock, control-plane/Cargo.toml, data-plane/Cargo.toml
We're currently working towards the next major release of Cages. To avoid conflicting releases between v0 and v1 in our staging environment, we need to migrate the control plane and data plane crates to v1. 
Update control plane and data plane packages to have new version `1.0.0-beta`
=> chore: bump control plane and data plane to new major version

.github/workflows/deploy-control-plane-image-production.yml, .github/workflows/deploy-control-plane-image-staging.yml, .github/workflows/deploy-data-plane-binary-production.yml, .github/workflows/deploy-data-plane-binary-staging.yml
Latest changes failed to compile in CI as the static build action was using an old version of rustc
Pin rust version to v1.73.0 stable
=> CI is using an old version of rust, update to 1.73.0 stable

data-plane/src/server/layers/attest.rs
Attestation check is comparing against the URI, which isn't matching.
Use the path getter to compare against
=> Update attestation uri check to compare against path

.github/workflows/deploy-control-plane-image-staging.yml
We should be able to look at debug logs in staging
Remove feature flag on staging build
=> Disable release logging in staging

control-plane/src/config_server.rs, control-plane/src/configuration.rs, data-plane/src/acme/cert.rs, data-plane/src/config_client.rs, data-plane/src/error.rs, data-plane/src/lib.rs
We need to provision a trusted cert for the new enclave domain.
Updated the acme flow to order certs for two domains:
* `cage-name.app-uuid.cage.evervault.com`
* `cage-name.app-uuid.enclave.evervault.com`
The acme process already handles multiple authorizations so it should automatically check that each domain is validated. The check in the control plane to check that we're only ordering ev enclave certs has also being updated.
I also did some small refactoring and logging for acme: 
I updated error handling for the JWS requests so that the error message is actually logged, rather that just the status code. We can do an overhaul to the whole config server to return error messages correctly but I didn't do that here as it was out of the scope of the PR.
I added logs to the top level acme …
=> [SPE-986] Expand trusted cert hostnames to handle the new enclave domain

data-plane/src/server/tls/cert_resolver.rs
When a request is made for `...enclave.evervault.com/dev`, we should serve the trusted cert.
Update check for serving trusted cert in resolver to include `enclave` as well as cage
=> [SPE-987] Update cert resolver to use trusted cert for enclave domain

data-plane/src/env/mod.rs, data-plane/src/health/initialized.rs, e2e-tests/mockCertProvisionerApi.js, e2e-tests/scripts/start_customer_process
Remove `cage` from the init flag so it can be removed in V1 cli
Remove `cage`
=> Remove cage from initialisation flag

data-plane/src/server/layers/auth.rs
Content type header has a typo in it which prevents the response from rendering in the browser
Correct typo.
=> Correct content type header for 401 response

control-plane/src/config_server.rs, data-plane/src/server/layers/context_log.rs, shared/src/logging.rs
Logs are still referring to Cages.
Update logging attributes to refer to enclaves
=> Update logging to use enclave in place of cage

data-plane/src/acme/cert.rs
If a customer migrates their cage, the new version won't reprovision a cert as it see's there's already one at `[cage-path]/certificate.pem`. We need migrated enclaves to provision a new cert which is valid for `.enclave.evervault.com`
Change key it's stored under in v1 to `certificate-v1.pem`
=> Update v1 acme certificate path

shared/src/lib.rs
An IP is hardcoded for local testing because `SO_ORIGINAL_DST` isn't set for docker on mac. We should look it up in the tests or use our own IP going forward because it has changed
Update the IP for now to fix e2es
=> Update egress IP for local testing

shared/src/server/egress.rs
Don't cache the lookup but dont cause it to fail
Dont error
=> Don't error on non ipv4 lookup

installer/scripts/compile-runtime-dependencies.sh
iptables wasn't being compiled as a static binary, so was not portable across distros
Correct LDFLAGS, lift env vars to above configure
=> Resolve static compilation of iptables by correcting LDFLAGS

.github/workflows/test-runtime-builder.yml, installer/Dockerfile, installer/scripts/compile-runtime-dependencies.sh, installer/scripts/installer.sh, installer/scripts/test-installer.sh, installer/test-abyss.Dockerfile, installer/test-alpine.Dockerfile, installer/test.Dockerfile
We need to include a portable binary for the `ip` command to work across distros as its needed in our new networking implementation.
- Pull iproute2 v6.7.0 into the installer (must be v6 as [any prior version isn't compatible with Musl](https://lore.kernel.org/netdev/20220806082406.216286-1-vincent@systemli.org/T/)).
- Extract iproute2 and perform a static compilation, reducing the compilation to only ip and the required libraries.
- Add testing action to build the installer and run it on a small sample of distros to verify that the binaries can be installed and run (with the exception of runit which exits with a non-zero code when run with any PID other than 1)
=> Resolve static compilation of ip

.github/workflows/deploy-runtime-installer-production.yml
The new production workflow was using staging creds
Fix
=> Fix AWS credentials for installer release

data-plane/src/dns/egressproxy.rs, docker-compose.yml, e2e-tests/run-all-feature-tests.sh, shared/src/lib.rs
The test IP was hardcoded
Get IP on test startup and export to env
=> Get test domain IP on test startup

control-plane/src/config_server.rs, data-plane/src/config_client.rs, data-plane/src/dns/egressproxy.rs, data-plane/src/lib.rs, data-plane/src/main.rs, data-plane/src/mocks/config_client_mock.rs, data-plane/src/time/mod.rs, docker-compose.yml, installer/test.Dockerfile, shared/src/server/config_server.rs
We have noticed large clock drifts in nitro enclaves, up to 6 seconds in a single week. There is no syncing mechanism out of the box for nitro enclaves so this PR adds a scheduled task to request the host's time and sets the enclave time to the same thing. TBC if this is sufficient
- Request the host time from the control plane periodically (5 mins atm)
- Log the time the request took to the control plane - we may need to account for this
- Set the time with `clock_settime` - its a POSIX compliant sys call so _should't_ cause us issues
=> Sync clock enclave clock with host instance

data-plane/src/time/mod.rs
From testing in staging the initial request to sync time takes 22 seconds because the request is made before the proxies stabilise. Every subsequent request is sub 1ms
```
[2024-01-24T11:09:02Z INFO  data_plane::time] Enclave time synced with host successfully - 1706094542.267s. Request round trip took 226018ms
[2024-01-24T11:10:16Z INFO  data_plane::time] Enclave time synced with host successfully - 1706094616.249s. Request round trip took 0ms
[2024-01-24T11:10:18Z INFO  data_plane::time] Enclave time synced with host successfully - 1706094618.152s. Request round trip took 0ms
```
- Skip the clock sync if request takes more than 500ms
- Log the request time in nanoseconds rather than ms so we can see how long it takes when successful
=> Skip clock sync if request took too long

data-plane/src/acme/cert.rs, data-plane/src/acme/provider.rs, data-plane/src/server/tls/tls_server.rs, data-plane/src/stats_client.rs, shared/src/stats.rs
Unwraps and metrics can be improved with acme to give us more observability into the acme order process.
Added extra logs
Removed unwrap when cert ordering fails and replace with proper shutdown. 
Started publishing stats on cert provider success or failure.
=> Add acme stats and improve failure

shared/src/logging.rs
Request type was introduced as a required field in the logging struct which breaks backwards compatibility. When using a new Control Plane with an old Data Plane, logs fail to deserialize when they reach the host.
Mark request type as an optional
=> Make request type optional to resolve breaking change

Cargo.lock, data-plane/Cargo.toml, data-plane/src/acme/cert.rs, data-plane/src/acme/directory.rs, data-plane/src/acme/error.rs, data-plane/src/acme/mod.rs, data-plane/src/acme/raw_cert.rs, data-plane/src/acme/utils.rs, data-plane/src/env/mod.rs, data-plane/src/lib.rs, data-plane/src/main.rs, data-plane/src/server/mod.rs, data-plane/src/server/tls/cert_resolver.rs, data-plane/src/server/tls/mod.rs, data-plane/src/server/tls/tls_server.rs, data-plane/src/server/tls/trusted_cert_container.rs
With the new instance refresh flow, we can no longer depend on each enclave being restarted every week for cert renewal. It used to work by checking if the cert needed renewal upon startup. 
*cert renewal*
When the cert is initially ordered, it sets the cert and then schedules a renewal task to run in 60 days + jitter of max 1 days (to account for multiple instances). This means the cert will be renewed if the enclave is never restarted.
If the cert already exists, on startup, the enclave will check the expiry date and set the renewal task to run 30 days before that.
*resolving cert*
Instead of passing the cert down to the resolver, we need to dynamically update the certificate used by the resolver so a RWLock was introduced. I used this over a mutex as the writes should only be on …
=> [SPE-1129] Update enclave to schedule trusted cert renewnal on startup

data-plane/src/acme/cert.rs
Deletion of the lock was added in last PR where it shouldn't be. We need to keep the lock on failure to track how many attempts have been made to fall back to ZeroSSL.
Remove line deleting lock and increase duration of polling for order
=> Fix trusted cert fallback

Cargo.lock, Cargo.toml, data-plane/Cargo.toml, shared/Cargo.toml
Dependabot flagged vulns in h2 and openssl.
- Migrate projects to use a shared openssl version
- Bump version of h2
=> Upgrade dependencies

control-plane/src/configuration.rs, control-plane/src/stats_proxy.rs, data-plane/src/acme/authorization.rs, data-plane/src/acme/order.rs
We need stats to be forwarded to cloudwatch and other metric agents if enabled by user (i.e. datadog) 
If feature is enabled send to both agents, otherwise send to one
=> Forward stats to cw and dd on enclave host

e2e-tests/e2e.js, shared/src/stats.rs
Datadog metrics are live in production but users see `cage_uuid` when querying
Update metric key
=> Rename cage to enclave for metrics

data-plane/src/acme/authorization.rs, data-plane/src/acme/order.rs, data-plane/src/crypto/parser.rs
Enclaves Data Plane's ciphertext parser was missing 2 version strings
Add support for QkTC and S0lS in the Data Plane ciphertext parser
=> Add support for QkTC and S0lS

control-plane/src/health.rs, control-plane/src/main.rs
It's difficult to tell when an Enclave was sent a sigterm. Should add an info log to always log it.
Add sigterm log and updated "cage" to "enclave" in healthcheck log
=> [ETR-2390] Add more logging to sigterm handling

Cargo.lock, control-plane/Cargo.toml, control-plane/src/dnsproxy.rs, control-plane/src/egressproxy.rs, control-plane/src/error.rs, control-plane/src/main.rs, data-plane/Cargo.toml, data-plane/src/dns/egressproxy.rs, data-plane/src/dns/enclavedns.rs, shared/src/acme/jws.rs, shared/src/server/egress.rs
Public internet egress currently relies on a single DNS Service provider. Extending this to use several providers with retry logic should remove the DNS Provider as a potential single point of failure.
- Update DNS proxy logic to expect a list of DNS Service IPs
- Randomly select 2 ips from the list for each connection, treating the first entry as the primary, and the second entry as secondary/fallback
- If the first DNS Provider fails for some reason (excl. the allow list being violated), then the dns request is retried against the secondary
=> Fix: update enclave dns proxy to support multiple dns service providers

Cargo.lock, control-plane/Cargo.toml, data-plane/Cargo.toml
The beta suffix is required to support testing preview images.
Restore beta suffix.
=> Restore beta tag suffix to crate versions

control-plane/src/dnsproxy.rs, control-plane/src/main.rs, data-plane/src/dns/enclavedns.rs
DNS Proxy running on the host needs to attempt connections against all hosts to make egress as reliable as possible.
Update proxy logic to iterate over all dns services and only exit when one resolves, or all have been attempted.
=> chore: Update control plane dns proxy to attempt dns lookup against all services until one resolves

.github/workflows/deploy-control-plane-image-production.yml, .github/workflows/deploy-control-plane-image-staging.yml, .github/workflows/deploy-data-plane-binary-staging.yml, .github/workflows/test-control-plane.yml, .github/workflows/test-data-plane.yml, .github/workflows/test-shared-lib.yml, .github/workflows/vsock-proxy.yml, control-plane/src/dnsproxy.rs, control-plane/src/main.rs, data-plane/src/dns/enclavedns.rs
We're updating the Enclave DNS providers to reduce the risk of single point of failure. To make this more robust, the providers are being interleaved so requests will be retried against alternate networks.
Update the list of dns providers to be a singleton containing all of the providers primaries followed by secondaries.
=> Interleave dns providers

.github/workflows/deploy-control-plane-image-production.yml, .github/workflows/deploy-control-plane-image-staging.yml, .github/workflows/deploy-data-plane-binary-staging.yml, .github/workflows/test-control-plane.yml, .github/workflows/test-data-plane.yml, .github/workflows/test-shared-lib.yml, .github/workflows/vsock-proxy.yml
CI is failing as the default toolchain was upgraded in Github Actions
Set override true to avoid compilation issues with time.
=> Override default toolchain in enclaves ci

.github/workflows/vsock-proxy.yml, Cargo.lock, control-plane/Cargo.toml, data-plane/Cargo.toml, e2e-tests/mock-crypto/Cargo.toml, shared/Cargo.toml
Rust builds were failing due to the use of an old time crate version 
Bump deps to all use compat version of time
=> Bump deps to fix rust build for 1.80.0

control-plane/src/egressproxy.rs, shared/src/utils.rs
Broken pipe errors are flooding the logs on every successful passthrough because copy_bidirectional does not shut down both directions when an EOF is sent on one https://docs.rs/tokio/latest/tokio/io/fn.copy_bidirectional.html
Ignore broken pipe errors, any other errors will still be surfaced. Other option here is to add our own impl but this will clean up the logs for now
=> Ignore broken pipe errors

data-plane/src/env/mod.rs, data-plane/src/main.rs
The data plane startup flow can run into errors seeding its environment. If these requests fail, the enclave can end up in a bad state and unable to correctly receive traffic.
Update the environment loading calls to retry multiple times before erroring.
=> Introduce retries to data plane environment init flow

data-plane/src/stats_client.rs, e2e-tests/e2e.js, shared/src/stats.rs
We need to track fds in use stats to monitor the enclave under heavy load
Use `/proc/sys/fs/file-nr` to get max, allocated and free fds
fd in use = allocated - free
[From kernel docs](https://www.kernel.org/doc/Documentation/sysctl/fs.txt):
> file-nr denote the number of allocated file handles, the number
of allocated but unused file handles, and the maximum number of
file handles
[this](https://www.netadmintools.com/how-many-open-files/) is worth a read re file-nr vs `lsof | wc -l`
=> Publish file descriptor stats to statsd

data-plane/src/cache.rs, data-plane/src/server/layers/attest.rs
We don't need to generate an AD on every single request. We can cache it and re-use the request.
Use existing cache lib with new cache for attestation doc that is evicted every five minutes.
=> ETR-2815 cache attestation docs

data-plane/src/env/mod.rs
The enclave needs to be more resilient to issues when fetching it's environment variables on start up. This currently leaves the enclave in a bad state if it fails.
Increase the backoff period for the env var loading to reduce the likelihood that it fails, ahead of a larger refactor.
=> Increase backoff for environment loading during init

Cargo.lock, data-plane/Cargo.toml, data-plane/src/health/agent.rs, data-plane/src/health/mod.rs, data-plane/src/health/notify_shutdown.rs, data-plane/src/lib.rs, data-plane/src/main.rs, shared/src/server/health.rs
The Enclave runs several services which are critical, but the health of these services is currently decoupled from the healthcheck system. To avoid issues when these services are unhealthy, we want to have a mechanism for these services to be able to notify the healthcheck agent so it can reflect the internal status.
- Implement future extension for `notify_shutdown` which uses a label and a channel to report the shutdown of a service which is expected to be running for the lifetime of the process
- If one of these futures completes, it will send its service label to the provided channel
- Update the healthcheck agent to expose a channel for sending shutdown notifications
- Update the healthcheck agent's healthcheck logic to check if any critical services have exited before attempting a …
=> Add shutdown mechanism for critical in-Enclave services

Cargo.lock, control-plane/Cargo.toml, control-plane/src/dnsproxy.rs, control-plane/src/health.rs, control-plane/src/main.rs, shared/src/notify_shutdown.rs, shared/src/server/health.rs
Follow on from https://github.com/evervault/enclaves/pull/256 which added more granular health checks to the data plane. This PR adds the same logic to critical control plane services
- Move the starting of services out of tokio::join and use tokio::spawn instead
- Add notify shutdown channel to update health check if a future completes
- Return 500 in healthcheck if any of the essential tasks have exited
=> Add notify shutdown to control plane services

control-plane/src/egressproxy.rs, control-plane/src/error.rs
Debugging egress networking currently involves using VPC flow logs. Logging the ip and hostname in the control plane will expose this info for easier debugging by users.
Log the host and ip when external connections are being created
=> Log external req ip and host

data-plane/src/lib.rs, data-plane/src/server/layers/attest.rs, data-plane/src/server/server.rs
Users need to be able to set cors on the .well-known/attestation endpoint if they are hitting it from the browser.
Pull it from the feature context passed through the docker file.
Start consuming cors context if passed from toml config: https://github.com/evervault/evervault-cli/pull/168
=> Add configurable cors origin header to attestation endpoint

control-plane/src/egressproxy.rs
We now support egress to non tls destinations so in some cases the SNI won't be present
Dont log hostname if SNI is missing
=> Dont log hostname for non tls egress

data-plane/src/server/server.rs
Codepath for handling websockets unconditionally attempted to auth the incoming request, even if the api key auth setting was disabled.
Check if api key auth is disabled before attempting auth. If its disabled, passthrough the req.
=> fix: only authenticate websocket requests when api key auth is enabled

Cargo.lock, Cargo.toml
Patch openssl version from `0.10.69` to `0.10.72`
=> chore: bump openssl version

data-plane/src/cert_provisioner_client/mod.rs, data-plane/src/crypto/api.rs, data-plane/src/crypto/attest.rs, data-plane/src/crypto/token.rs, data-plane/src/server/layers/attest.rs, data-plane/src/server/tls/cert_resolver.rs
We want to support the generation of attestation documents containing public keys to allow use of the KMS <> Nitro integration.
Include an optional public key argument in the attest endpoint, which is taken as a base64 encoded string. If set, it is provided to the NSM API call as the `public_key` argument.
=> feat: expose optional public key parameter on the attestation doc internal endpoint

data-plane/src/dns/egressproxy.rs
The in-Enclave egress proxy attempted to read an initial packet before forwarding the egress target details to the host. This was leftover from an initial assumption that the connection would be TLS encrypted, however this is likely now causing issues for non-HTTPS egress.
For example, MySQL clients expect a packet to be sent by the server before the client will send any data. When put through this code path, the egress connection hangs indefinitely waiting for data from the client.
Use read with timeout on incoming sockets. Send egress packet to host to open connection to remote, before piping the connection in both directions.
=> Fix: remove initial read on egress connections as its no longer needed
